#!/usr/bin/env python3
"""
Generate everything report/model_report.tex cites: numbers.tex (a macro per
quoted figure), tab_*.tex (tables), and figs/*.png (report-only figures,
rendered with the same backend as the abstract's). The report never contains
a typed number, so recompiling after a model rerun updates all of it.

    py -3.12 scripts/make_report_assets.py
"""
from __future__ import annotations

import json
import shutil
import sqlite3
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import make_abstract_figures as F                                  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
REP = ROOT / "report"
FIGS = REP / "figs"
M = json.loads((ROOT / "db" / "direction_model.json").read_text(encoding="utf-8"))
try:
    REC = json.loads((ROOT / "db" / "direction_recovery.json").read_text(encoding="utf-8"))
except FileNotFoundError:
    REC = None

LN2 = 0.6931471805599453


# ---------------------------------------------------------------- helpers
def tex_int(n):
    return f"{n:,}".replace(",", "{,}")


def macro(name, value):
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def corpus_stats():
    con = sqlite3.connect(ROOT / "db" / "atlas.sqlite")
    total = con.execute("select count(*) from inscriptions").fetchone()[0]
    bylang = con.execute("""
        select coalesce(l.name,'(unrecorded)'), count(*),
               sum(case when i.direction_id is not null then 1 else 0 end)
        from inscriptions i left join languages l on l.id=i.language_id
        group by 1 order by 2 desc""").fetchall()
    codes = dict(con.execute("""
        select d.code, count(*) from inscriptions i
        join directions d on d.id=i.direction_id group by 1""").fetchall())
    pile = con.execute("""
        select count(*) from inscriptions i join quarters q
        on q.ord = i.q_ord_start where q.edge = -400""").fetchone()[0]
    widths = [r[0] for r in con.execute("""
        select i.q_ord_end - i.q_ord_start + 1 from inscriptions i
        join directions i2 on i2.id = i.direction_id
        where i.q_ord_start is not null""").fetchall()]
    con.close()
    return total, bylang, codes, pile, np.array(widths)


# ---------------------------------------------------------------- numbers.tex
def write_numbers(total, codes, pile, widths):
    lad = M["ladder"]
    v = M["variance_share_full_model"]
    pairs = M["cv_pairs"]
    k = M["st_kernel"]
    ct = M.get("contact_test", {})
    fr = ct.get("fitted_rate", {})

    def met(model, field, fmt="{:.3f}"):
        return fmt.format(lad[model]["metrics"][field])

    def pair(key, field, flip=False, fmt="{:+.4f}"):
        x = pairs[key][field]
        return fmt.format(-x if flip else x)

    L = ["% generated by scripts/make_report_assets.py — do not edit"]
    a = L.append
    a(macro("NCorpus", tex_int(total)))
    a(macro("NModelled", tex_int(M["n_modelled"])))
    a(macro("NFindspots", tex_int(M["n_findspots"])))
    a(macro("NDroppedNoXY", tex_int(M.get("n_dropped_no_coordinates", 0))))
    a(macro("NMessy", tex_int(M["n_excluded_messy"])))
    a(macro("NLang", str(len(M["languages"]))))
    a(macro("NAlph", str(len(M["alphabets"]))))
    a(macro("NBoot", str(M.get("n_bootstrap", ""))))
    a(macro("Prevalence", f"{lad['M0 intercept']['metrics']['prevalence']*100:.1f}"))
    a(macro("PileFourHundred", tex_int(pile)))
    a(macro("MedianIntervalQ", str(int(np.median(widths)))))
    a(macro("PctWideInterval", f"{100*float((widths>=4).mean()):.0f}"))
    a(macro("CodeZero", tex_int(codes.get("0", 0))))
    a(macro("CodeOne", tex_int(codes.get("1", 0))))
    a(macro("CodeTwo", tex_int(codes.get("2", 0))))
    a(macro("CodeThree", tex_int(codes.get("3", 0))))

    a(macro("KernelName", "Mat\\'ern 3/2" if k["kernel"] == "m32"
            else "squared-exponential"))
    a(macro("KernelLs", f"{k['length_scale_km']:.0f}"))
    a(macro("KernelRidge", f"{k['ridge']:g}"))
    a(macro("KernelKnots", str(k["spatial_knots"])))
    a(macro("KernelTKnots", str(k["time_knots"])))
    a(macro("KernelLt", f"{k['length_scale_quarters']:g}"))

    a(macro("BitsField", met("M1b space-time kernel", "log_loss_bits")))
    a(macro("FOneField", met("M1b space-time kernel", "f1")))
    a(macro("FOneLang", met("M2 + language", "f1")))
    a(macro("FOneAlph", met("M2a alphabet, no language", "f1")))
    a(macro("BitsLang", met("M2 + language", "log_loss_bits")))
    a(macro("BitsAlph", met("M2a alphabet, no language", "log_loss_bits")))
    a(macro("BitsFull", met("M7 + space-time kernel", "log_loss_bits")))
    a(macro("FOneFull", met("M7 + space-time kernel", "f1")))
    a(macro("PrAucFull", met("M7 + space-time kernel", "pr_auc")))

    a(macro("DeltaAlphLang", pair("alphabet alone vs language alone", "delta_bits", flip=True, fmt="{:.4f}")))
    a(macro("DeltaAlphLangLo", pair("alphabet alone vs language alone", "hi", flip=True, fmt="{:.4f}")))
    a(macro("DeltaAlphLangHi", pair("alphabet alone vs language alone", "lo", flip=True, fmt="{:.4f}")))
    a(macro("DeltaAddLang", pair("adding language to alphabet", "delta_bits")))
    a(macro("DeltaAddLangLo", pair("adding language to alphabet", "lo")))
    a(macro("DeltaAddLangHi", pair("adding language to alphabet", "hi")))
    a(macro("DeltaField", pair("geography + field beyond M5", "delta_bits")))
    a(macro("DeltaFieldLo", pair("geography + field beyond M5", "lo")))
    a(macro("DeltaFieldHi", pair("geography + field beyond M5", "hi")))

    a(macro("VarAlph", f"{v['alphabet']*100:.1f}"))
    a(macro("VarAlphTotal", f"{v['alphabet total (levels + curves)']*100:.1f}"))
    a(macro("VarLang", f"{v['language']*100:.1f}"))
    a(macro("VarField", f"{v['space-time field']*100:.1f}"))
    a(macro("VarGeo", f"{v['geography']*100:.1f}"))
    a(macro("VarFindspot", f"{v['findspot']*100:.1f}"))
    a(macro("CorrLangAlph", f"{v['component correlations |r| >= 0.3'].get('language ~ alphabet', 0):.2f}"))

    sc = M.get("structure_checks", {}).get("paired_vs_reference", {})
    ng = sc.get("M5 without the global curve", {})
    qd = sc.get("M5 quadrature-in-kernel, no EM", {})
    a(macro("DeltaNoG", f"{ng.get('delta_bits', 0):+.4f}"))
    a(macro("DeltaNoGLo", f"{ng.get('lo', 0):+.4f}"))
    a(macro("DeltaNoGHi", f"{ng.get('hi', 0):+.4f}"))
    a(macro("DeltaQuad", f"{qd.get('delta_bits', 0):+.4f}"))
    a(macro("DeltaQuadLo", f"{qd.get('lo', 0):+.4f}"))
    a(macro("DeltaQuadHi", f"{qd.get('hi', 0):+.4f}"))

    if ct:
        a(macro("ContactN", tex_int(ct["n"])))
        a(macro("ContactOR", f"{ct['d_latin']['odds_ratio']:.3f}"))
        a(macro("ContactORLo", f"{ct['d_latin']['or_lo']:.3f}"))
        a(macro("ContactORHi", f"{ct['d_latin']['or_hi']:.3f}"))
        a(macro("ContactNear", f"{fr['p_near']*100:.1f}"))
        a(macro("ContactFar", f"{fr['p_far']*100:.1f}"))
        a(macro("ContactKmNear", f"{fr['km_near']:.0f}"))
        a(macro("ContactKmFar", f"{fr['km_far']:.0f}"))
        a(macro("ContactGapLo", f"{fr['gap_lo']*100:+.2f}"))
        a(macro("ContactGapHi", f"{fr['gap_hi']*100:+.2f}"))

    cells = M.get("cells", {})
    el = cells.get("Etruscan | Republican Latin alphabet", {})
    a(macro("EtrInLatin", f"{el.get('p', 0)*100:.0f}"))
    a(macro("EtrInLatinMass", tex_int(int(el.get("mass", 0)))))
    sz = cells.get("Raetic | Sanzeno alphabet", {})
    mg = cells.get("Raetic | Magrè alphabet", {})
    a(macro("RaeticSanzeno", f"{sz.get('p', 0)*100:.0f}"))
    a(macro("RaeticMagre", f"{mg.get('p', 0)*100:.0f}"))

    def cent(alph, c):
        rows = [r for r in M["trajectories"].get(alph, [])
                if (abs(r["year"]) - 1) // 100 + 1 == c]
        if not rows:
            return 0
        return round(100 * sum(r["p"] * r["mass"] for r in rows)
                     / sum(r["mass"] for r in rows))

    a(macro("LepThird", str(cent("Lepontic alphabet", 3))))
    a(macro("LepFirst", str(cent("Lepontic alphabet", 1))))
    a(macro("GreekRedSixth", str(cent("Greek alphabet (red type)", 6))))
    a(macro("GreekRedFifth", str(cent("Greek alphabet (red type)", 5))))
    a(macro("PooledSixth", str(cent("", 6))))
    a(macro("PooledSecond", str(cent("", 2))))
    a(macro("PooledFirst", str(cent("", 1))))

    es = M.get("etruscan_spatial", {})
    a(macro("MoranRaw", f"{es.get('raw_rate', {}).get('morans_I', 0):.3f}"))
    a(macro("MoranRawP", f"{es.get('raw_rate', {}).get('p', 1):.3f}"))
    a(macro("MoranRes", f"{es.get('model_residual', {}).get('morans_I', 0):.3f}"))
    a(macro("MoranResP", f"{es.get('model_residual', {}).get('p', 1):.3f}"))
    ps = M.get("pooled_spatial", {})
    a(macro("MoranPooled", f"{ps.get('morans_I', 0):.3f}"))
    a(macro("MoranPooledP", f"{ps.get('p', 1):.3f}"))

    if REC:
        s = REC["summary"]
        a(macro("RecEM", f"{s['aoristic EM']['overall_rmse']:.3f}"))
        a(macro("RecMid", f"{s['midpoint']['overall_rmse']:.3f}"))
        a(macro("RecNarrow", f"{s['narrow only']['overall_rmse']:.3f}"))

    rk = M.get("rank_checks", {})
    if rk:
        mods, pv = rk["models"], rk["paired_vs_M5"]
        a(macro("HsgpCols", str(rk["hsgp_columns"])))
        a(macro("DenseKnots", str(rk["dense_knots"])))
        a(macro("HsgpAloneBits", f"{mods['hsgp field alone']['metrics']['log_loss_bits']:.3f}"))
        a(macro("KnotAloneBits", f"{mods['knot field alone']['metrics']['log_loss_bits']:.3f}"))
        a(macro("DenseAloneBits", f"{mods['knot-dense field alone']['metrics']['log_loss_bits']:.3f}"))
        a(macro("HsgpOnTop", f"{pv['M5 + hsgp field']['delta_bits']:+.4f}"))
        a(macro("HsgpOnTopLo", f"{pv['M5 + hsgp field']['lo']:+.4f}"))
        a(macro("HsgpOnTopHi", f"{pv['M5 + hsgp field']['hi']:+.4f}"))
        a(macro("KnotOnTop", f"{pv['M5 + knot field']['delta_bits']:+.4f}"))
        a(macro("KnotOnTopLo", f"{pv['M5 + knot field']['lo']:+.4f}"))
        a(macro("KnotOnTopHi", f"{pv['M5 + knot field']['hi']:+.4f}"))
        a(macro("DenseOnTop", f"{pv['M5 + knot-dense field']['delta_bits']:+.4f}"))
        a(macro("FOneHsgpOnTop", f"{mods['M5 + hsgp field']['metrics']['f1']:.3f}"))

    (REP / "numbers.tex").write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"numbers.tex: {len(L)-1} macros")


# ---------------------------------------------------------------- tables
bs2 = chr(92)
def write_table(name, colspec, header, rows):
    """A complete tabular: input inside an alignment cannot cross EOF,
    so each table ships as one whole environment."""
    L = [bs2 + 'begin{tabular}{' + colspec + '}',
         bs2 + 'hline' + bs2 + 'hline',
         header + ' ' + bs2 + bs2,
         bs2 + 'hline'] + rows + [bs2 + 'hline' + bs2 + 'hline',
         bs2 + 'end{tabular}']
    (REP / ('tab_' + name + '.tex')).write_text(chr(10).join(L) + chr(10), encoding='utf-8')



def write_tables(bylang):
    lad = M["ladder"]
    rows = []
    order = ["M0 intercept", "M1 + century", "M1b space-time kernel",
             "M2 + language", "M2a alphabet, no language", "M3 + alphabet",
             "M4 + alphabet x time", "M5 + findspot", "M6 + geography",
             "M7 + space-time kernel"]
    label = {"M0 intercept": "M0: intercept only",
             "M1 + century": "M1: global time curve",
             "M1b space-time kernel": "M1b: space--time field",
             "M2 + language": "M2: language levels",
             "M2a alphabet, no language": "M2a: alphabet levels",
             "M3 + alphabet": "M3: language + alphabet",
             "M4 + alphabet x time": "M4: + per-alphabet curves",
             "M5 + findspot": "M5: + findspot effects",
             "M6 + geography": "M6: + distances",
             "M7 + space-time kernel": "M7: + space--time field"}
    for k in order:
        m = lad[k]["metrics"]
        rows.append(f"{label[k]} & {m['log_loss_bits']:.3f} & {m['precision']:.3f}"
                    f" & {m['recall']:.3f} & {m['f1']:.3f} & {m['pr_auc']:.3f}"
                    f" & {m['roc_auc']:.3f} \\\\")
    write_table("ladder", "lrrrrrr", "model & bits & precision & recall & F1 & PR-AUC & ROC-AUC", rows)

    rows = []
    for lang, tot, cod in bylang:
        pct = 100 * (cod or 0) / tot
        rows.append(f"{lang} & {tot:,} & {(cod or 0):,} & {pct:.0f}\\% \\\\"
                    .replace(",", "{,}"))
    write_table("coverage", "lrrr", "language & inscriptions & direction coded & coverage", rows)

    v = M["variance_share_full_model"]
    keys = [("alphabet levels", "alphabet"), ("language levels", "language"),
            ("per-alphabet curves", "alphabet x time"),
            ("findspot effects", "findspot"), ("distances", "geography"),
            ("space--time field", "space-time field"),
            ("global time curve", "time curve")]
    rows = [f"{lab} & {v[k]*100:+.1f}\\% \\\\" for lab, k in keys if k in v]
    write_table("variance", "lr", "term & share of fitted variance", rows)

    sel = M["st_kernel"].get("selection", [])
    rows = []
    for s in sel:
        kern = "Mat\\'ern 3/2" if s["kernel"] == "m32" else "sq.\\ exp."
        lt = s.get("lt", M["st_kernel"]["length_scale_quarters"])
        rows.append(f"{kern} & {s['length_scale_km']:.0f} & {s.get('ridge','--')}"
                    f" & {lt:g} & {s['spatial_knots']} & {s['cv_neg_loglik']:.4f} \\\\")
    write_table("sweep", "lrrrrr", "kernel & length scale (km) & ridge & temporal scale & knots & CV loss", rows)

    cells = M.get("cells", {})
    rows = []
    for key in sorted(cells, key=lambda k: -cells[k]["mass"]):
        c = cells[key]
        lang, alph = key.split(" | ")
        rows.append(f"{lang} & {alph} & {c['mass']:.0f} & {c['p']*100:.1f}\\% \\\\")
    write_table("cells", "llrr", "language & alphabet & aoristic mass & fitted percent dextroverse", rows)

    if REC:
        s = REC["summary"]
        trads = sorted(s["aoristic EM"]["per_tradition_rmse"])
        rows = []
        for tr in trads:
            cells_ = " & ".join(f"{s[k]['per_tradition_rmse'].get(tr, float('nan')):.3f}"
                                for k in ("aoristic EM", "midpoint", "narrow only"))
            rows.append(f"{tr} & {cells_} \\\\")
        cells_ = " & ".join(f"{s[k]['overall_rmse']:.3f}"
                            for k in ("aoristic EM", "midpoint", "narrow only"))
        rows.append(f"\\hline overall & {cells_} \\\\")
        write_table("recovery", "lrrr",
                    "tradition & aoristic EM & midpoint & narrow only", rows)

    counts = M.get("counts_by_alphabet", {})
    rows = []
    for alph in sorted(counts, key=lambda k: -counts[k]["n"]):
        c = counts[alph]
        rows.append(f"{alph} & {c['n']:,} & {c['raw_dextro']*100:.1f}\\% \\\\"
                    .replace(",", "{,}").replace("–", "--"))
    write_table("alphabets", "lrr",
                "alphabet group & records & raw \\% dextroverse", rows)

    corr = M["variance_share_full_model"].get(
        "component correlations |r| >= 0.3", {})
    rows = [f"{k.replace('~', 'and').replace('x', '$\\times$')} & {v:+.2f} \\\\"
            for k, v in sorted(corr.items(), key=lambda kv: -abs(kv[1]))]
    write_table("corr", "lr", "component pair & correlation $r$", rows)
    print("tables written")


# ---------------------------------------------------------------- figures
def fig_coverage(bylang):
    c = F.Canvas()
    W, RH = 6.0, 0.34
    langs = [(l, t, cd or 0) for l, t, cd in bylang if t >= 40]
    top = len(langs) * RH
    mx = max(t for _, t, _ in langs)
    for v in (0, 5000, 10000):
        x = v / mx * W
        c.add(F.Line([(x, 0), (x, top)], F.mix(F.RULE, 60)))
        c.add(F.Text(x, top, f"{v:,}", "above", 2))
    y = top
    for lang, tot, cod in langs:
        y -= RH
        cy = y + RH / 2
        c.add(F.Text(0, cy, lang, "left", 4))
        c.add(F.Rect(0, cy - 0.09, tot / mx * W, cy + 0.09, F.mix(F.MID, 30), fill=True))
        if cod:
            c.add(F.Rect(0, cy - 0.09, cod / mx * W, cy + 0.09, F.mix(F.LTR, 75), fill=True))
        c.add(F.Text(tot / mx * W + 0.05, cy, f"{100*cod/tot:.0f}\\%", "right", 2))
    c.add(F.Text(W / 2, 0, "inscriptions (dark: direction coded)", "below", 8))
    return c


def fig_widths(widths):
    c = F.Canvas()
    W, H = 6.4, 2.6
    bins = [(1, "25 yr"), (2, "50"), (3, "75"), (4, "100"), (8, "200"),
            (12, "300"), (16, "400"), (999, "over 400")]
    counts, prev = [], 0
    w = widths[np.isfinite(widths)]
    for ub, _ in bins:
        counts.append(int(((w > prev) & (w <= ub)).sum()))
        prev = ub
    mx = max(counts)
    bw = W / len(bins)
    for i, ((_, lab), n) in enumerate(zip(bins, counts)):
        x = i * bw
        c.add(F.Rect(x + 0.06, 0, x + bw - 0.06, n / mx * H, F.mix(F.LTR, 70), fill=True))
        c.add(F.Text(x + bw / 2, n / mx * H, f"{n:,}", "above", 2))
        c.add(F.Text(x + bw / 2, 0, lab, "below", 2))
    c.add(F.Text(W / 2, -0.42, "width of the dating interval", "below", 3))
    return c


def fig_map():
    import direction_model as D
    df, *_ = D.load()
    g = df.groupby("place_id").agg(x=("px", "first"), y=("py", "first"),
                                   n=("y", "size"), p=("y", "mean"))
    c = F.Canvas()
    W = 6.2
    x0, x1 = g.x.min(), g.x.max()
    y0, y1 = g.y.min(), g.y.max()
    Hm = W * (y1 - y0) / (x1 - x0)
    for _, r in g.iterrows():
        px = (r.x - x0) / (x1 - x0) * W
        py = (r.y - y0) / (y1 - y0) * Hm
        rad = max(0.018, min(0.12, (r.n ** 0.5) / 45))
        c.add(F.Dot(px, py, rad, F.colour(r.p)))
    c.add(F.Text(W / 2, -0.1,
                 "findspots, sized by inscriptions, coloured by share dextroverse",
                 "below", 3))
    return c


def fig_sweep():
    sel = M["st_kernel"].get("selection", [])
    best = {}
    for s in sel:
        key = (s["kernel"], s["length_scale_km"])
        if "lt" in s:
            continue
        best[key] = min(best.get(key, 9e9), s["cv_neg_loglik"])
    if not best:
        return None
    c = F.Canvas()
    W, H = 5.2, 2.6
    lss = sorted({k[1] for k in best})
    vals = [v for v in best.values()]
    lo, hi = min(vals), max(vals)
    pad = (hi - lo) * 0.15 + 1e-9

    def X(ls): return (lss.index(ls) / max(len(lss) - 1, 1)) * W
    def Y(v): return (v - lo + pad) / (hi - lo + 2 * pad) * H

    for kern, col, lab in [("se", F.mix(F.MID, 70), "squared-exponential"),
                           ("m32", F.LTR, "Mat\\`ern 3/2")]:
        pts = [(X(ls), Y(best[(kern, ls)])) for ls in lss if (kern, ls) in best]
        if not pts:
            continue
        c.add(F.Line(pts, col, width=1.2))
        for p in pts:
            c.add(F.Dot(p[0], p[1], 0.06, col))
        c.add(F.Text(pts[-1][0] + 0.1, pts[-1][1], lab, "right", 2, col=col))
    for ls in lss:
        c.add(F.Text(X(ls), 0, f"{ls:.0f} km", "below", 3))
    c.add(F.Text(0, H / 2, "held-out loss", "above", 16, rotate=90))
    c.add(F.Text(W / 2, -0.4, "kernel length scale (best ridge per point)", "below", 3))
    return c


def fig_forest():
    geo = M.get("geography", {})
    ct = M.get("contact_test", {})
    entries = [(f"corpus-wide: {k.replace('d_', 'distance to ')}",
                v["odds_ratio"], v.get("or_lo"), v.get("or_hi"))
               for k, v in geo.items()]
    if ct:
        d = ct["d_latin"]
        entries.append(("Etruscan alphabets only: distance to Latin",
                        d["odds_ratio"], d.get("or_lo"), d.get("or_hi")))
    c = F.Canvas()
    W, RH = 5.6, 0.34
    top = len(entries) * RH
    lo_x, hi_x = 0.55, 1.45

    def X(v): return (min(max(v, lo_x), hi_x) - lo_x) / (hi_x - lo_x) * W

    for v in (0.6, 0.8, 1.0, 1.2, 1.4):
        c.add(F.Line([(X(v), 0), (X(v), top)],
                     F.RULE if v == 1.0 else F.mix(F.RULE, 55), dashed=(v == 1.0)))
        c.add(F.Text(X(v), top, f"{v:g}", "above", 2))
    y = top
    for lab, orr, lo, hi in entries:
        y -= RH
        cy = y + RH / 2
        c.add(F.Text(0, cy, lab, "left", 4))
        if lo is not None and hi is not None:
            c.add(F.Line([(X(lo), cy), (X(hi), cy)], F.mix(F.MID, 85), width=1.0))
        c.add(F.Dot(X(orr), cy, 0.07, F.LTR if orr < 1 else F.mix(F.RTL, 80, F.MID)))
    c.add(F.Text(W / 2, 0, "odds ratio per log-km (95\\% cluster bootstrap)", "below", 8))
    return c


def main():
    REP.mkdir(exist_ok=True)
    FIGS.mkdir(exist_ok=True)
    total, bylang, codes, pile, widths = corpus_stats()
    write_numbers(total, codes, pile, widths)
    write_tables(bylang)

    for name, canvas in [("coverage", fig_coverage(bylang)),
                         ("widths", fig_widths(widths)),
                         ("map", fig_map()),
                         ("sweep", fig_sweep()),
                         ("forest", fig_forest())]:
        if canvas is None:
            continue
        size = F.render(canvas, FIGS / f"{name}.png")
        print(f"figs/{name}.png {size}")

    for src in ["fig1.png", "fig2.png", "fig3.png"]:
        shutil.copy(ROOT / "abstract" / src, FIGS / src)
    print("abstract figures copied")


if __name__ == "__main__":
    main()
